server:
  port: 8082
  servlet:
    context-path: /ui
    session:
      cookie:
        name: UISESSION

security:
  basic:
    enabled: false

  oauth2:

    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8081/auth/user/me


spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:~/data;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    serialization:
      write_dates_as_timestamps: false
